default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= Rails.application.secrets[:database][:host] %>
  database: <%= Rails.application.secrets[:database][:database] %>_<%= Rails.env %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>

development: *default
test: *default
production: *default
